#pragma once

#include "AddressCompletionPopup.h"
#include "AddressLineEdit.h"
#include "AddressSuggestion.h"
#include "ApplicationLaunch.h"
#include "BookmarkStore.h"
#include "BrowserPreferences.h"
#include "BrowserShortcut.h"
#include "BrowserTabBar.h"
#include "CrossDomainPresetCatalog.h"
#include "CrossDomainPolicySnapshot.h"
#include "CrossDomainPromptController.h"
#include "CrossDomainRequestInterceptor.h"
#include "CrossDomainSettings.h"
#include "DomainPatternMatcher.h"
#include "BrowserDataCleanup.h"
#include "BrowserInteraction.h"
#include "BrowserProfile.h"
#include "CertificateTrustValidator.h"
#include "DetachedVideoWindow.h"
#include "DownloadHistoryStore.h"
#include "DnsSettings.h"
#include "ExternalNavigationPolicy.h"
#include "FindBar.h"
#include "GeneralSettingsPage.h"
#include "HistoryStore.h"
#include "HttpAuthenticationController.h"
#include "Localization.h"
#include "PageZoom.h"
#include "PermissionPolicy.h"
#include "ProxySettings.h"
#include "ProxyAuthenticationController.h"
#include "SessionStore.h"
#include "SearchSettings.h"
#include "SettingsDialog.h"
#include "SettingsSaveTransaction.h"
#include "SiteDomain.h"
#include "TrustConfiguration.h"
#include "TrustCertificateRepository.h"
#include "TrustRulesSettingsPage.h"
#include "TrustSettings.h"
#include "WebAppStore.h"
#include "WebAppShortcutManager.h"
#include "WindowPlacement.h"
#include "WindowChrome.h"

#include <QApplication>
#include <QAuthenticator>
#include <QCheckBox>
#include <QCloseEvent>
#include <QDialog>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QHBoxLayout>
#include <QLabel>
#include <QKeyEvent>
#include <QLineEdit>
#include <QListWidget>
#include <QMouseEvent>
#include <QNetworkProxy>
#include <QNetworkProxyFactory>
#include <QPlatformSurfaceEvent>
#include <QProcess>
#include <QPushButton>
#include <QSignalSpy>
#include <QStackedWidget>
#include <QSettings>
#include <QTemporaryDir>
#include <QTest>
#include <QTimer>
#include <QTimeZone>
#include <QTranslator>
#include <QUuid>
#include <QWebEnginePage>
#include <QWebEngineView>
#include <QWindow>
